name: build and deploy node

on:
  workflow_call:
    inputs:
      USE_YARN:
        required: false
        default: "true"
        type: string
      NODE_VERSION:
        required: true
        type: string
      CI:
        required: false
        default: "true"     
        type: string
      DOCKER_REPO:
         required: true
         type: string
      DOCKER_REGISTRY:
        required: false
        default: "registry.hub.docker.com"
        type: string
      DOCKER_USER:
        required: true
        type: string
      QEMU_SETUP:
        required: false
        default: "true"
        type: string
      DEPLOY_URL: 
        required: false
        default: "INVALID"        
        type: string
      USE_PULL_REPO:
        required: false
        type: string        
        default: "false"
      USE_ENV_FILES: 
        required: false
        default: "true"        
        type: string             
    secrets:
      DOCKER_PASSWORD:
        required: true
      AUTH_TOKEN:
        required: true
        
jobs:
  node_build:
    name: "build node docker image and deploy"
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: [ubuntu-latest] 
   
    steps:
        
      - uses: actions/checkout@v3

      - name: Read env
        uses: bitbool-actions/read-env@main
        id: read_env
        with:
          USE_ENV_FILES: "${{ inputs.USE_ENV_FILES }}"

      - name: set deploy url env var from input
        shell: bash
        run: |
          echo DEPLOY_URL=${{ inputs.DEPLOY_URL }} >> $GITHUB_ENV
        if: ${{ inputs.DEPLOY_URL != 'INVALID' }}

      - name: node build
        uses: bitbool-actions/node-build@master
        id: node_build
        with:
          USE_YARN: "${{ inputs.USE_YARN }}"
          CI: "${{ inputs.CI }}"
          NODE_VERSION: "${{ inputs.NODE_VERSION }}"

      - name: docker prepare
        uses: bitbool-actions/docker-prepare@main
        id: docker_prepare
        with:
          DOCKER_REGISTRY: "${{ inputs.DOCKER_REGISTRY }}"
          DOCKER_REPO: "${{ inputs.DOCKER_REPO }}"
          QEMU_SETUP: "${{ inputs.QEMU_SETUP }}"
          DOCKER_USER: "${{ inputs.DOCKER_USER }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.docker_prepare.outputs.tags }}
          push: true
        
      - uses: bitbool-actions/docker-compose-deploy@master
        id: docker_deploy
        with:
          AUTH_TOKEN: "${{ secrets.AUTH_TOKEN }}"
          USE_PULL_REPO: "${{ inputs.USE_PULL_REPO }}"
          DEPLOY_URL: "${{ env.DEPLOY_URL }}"
          IMAGES: "${{ steps.docker_prepare.outputs.images_with_tags }}"
